export const data = [
  {
    id: 0,
    On: "on",
    icon: <img src="icons/first.png" alt="error" />,
    campaign: "Blueberry Cake Campaign",
    date: "25 july 22-01 Aug 22",
    clicks: 300,
    Budget: "INR 3400",
    location: "chennai",
    plateform: "facebook",
    platform: <img src="icons/facebook.png" />,
    status: "live",
    actions: [<img src="icons/edit.png" />, <img src="icons/trash.png" />],
  },
  {
    id: 1,
    On: "on",
    icon: <img src="icons/second.png" />,
    campaign: "chocolate Cake Campaign",
    date: "25 july 22-01 Aug 22",
    clicks: 300,
    Budget: "INR 3400",
    location: "chennai",
    plateform: "facebook",
    platform: <img src="icons/facebook.png" />,
    status: "paused",
    actions: [<img src="icons/edit.png" />, <img src="icons/trash.png" />],
  },
  {
    id: 2,
    On: "on",
    icon: <img src="icons/third.png" />,
    campaign: "Brownie Cake Campaign",
    date: "25 july 22-01 Aug 22",
    clicks: 300,
    Budget: "INR 3400",
    location: "chennai",
    plateform: "facebook",
    platform: <img src="icons/facebook.png" />,
    status: "paused",
    actions: [<img src="icons/edit.png" />, <img src="icons/trash.png" />],
  },
  {
    id: 3,
    On: "on",
    icon: <img src="icons/fourth.png" />,
    campaign: "Pumpkin Cakes Campaign",
    date: "25 july 22-01 Aug 22",
    clicks: 300,
    Budget: "INR 3400",
    location: "chennai",
    plateform: "youtube",
    platform: <img src="icons/youtube.png" />,
    status: "paused",
    actions: [<img src="icons/edit.png" />, <img src="icons/trash.png" />],
  },
  {
    id: 4,
    On: "on",
    icon: <img src="icons/fifth.png" />,
    campaign: "Cup Cakes Campaign",
    date: "25 july 22-01 Aug 22",
    clicks: 300,
    Budget: "INR 3400",
    location: "chennai",
    plateform: "youtube",
    platform: <img src="icons/youtube.png" />,
    status: "paused",
    actions: [<img src="icons/edit.png" />, <img src="icons/trash.png" />],
  },
];
